Mridul-1-Sharma/Hacktoberfest2022-DataStructuresAndAlgorithms

Cpp/kadanes_algo

The idea of Kadane’s algorithm is to maintain a variable max_ending_here that stores the maximum sum contiguous subarray ending at current index and a variable max_so_far stores the maximum sum of contiguous subarray found so far, Everytime there is a positive-sum value in max_ending_here compare it with max_so_far and update max_so_far if it is greater than max_so_far.

Kadanes_algo

---

Cpp/Radix_sort

The idea of Radix Sort is to do digit by digit sort starting from least significant digit to most significant digit. Radix sort uses counting sort as a subroutine to sort.

Radix_Sort

---

contribution.md

solve issue `Create contribution.md as it is empty`

---

java/searching/LinearSearch.java

Program for linear search algorithm in Java

Add linear search algorithm in Java

---

Cpp/dynamicProgramming/longestCommonSubsequence.cpp

A c++ program for longest common subsequence using dynamic programming

longestCommonSubsequence.cpp

---

Cpp/Prims_min_span_tree

Prim’s algorithm is used to find the Minimum Spanning Tree for a given graph. Prim’s algorithm starts with a single node and works its way through several adjacent nodes, exploring all of the connected edges along the way.

Prims_min_span_tree

---

Cpp/Sparse_matrix

A matrix is a two-dimensional data object made of m rows and n columns, therefore having total m x n values. If most of the elements of the matrix have 0 value, then it is called a sparse matrix.The above program also finds the sum of two sparse matrices

Sparse_matrix

---

python/sorting/radixSort.py

Kindly review & merge followed by providing hacktoberFest acceptance tag.

radixSort.py

---

Cpp/Set_Operations_on_Arrays

The following program performs set operations-Union, intersection and difference on arrays

Set_Operations_on_Arrays

---

Cpp/Sieve-of-Eratosthenes

Sieve of Eratosthenes is an algorithm for finding all the prime numbers in range [1,n] (n<10000000) using  O(n log log n) operations. The sieve of Eratosthenes is one of the most efficient ways to find all primes smaller than n when n is smaller than 10 million.

Sieve-of-Eratosthenes

---

Cpp/Knuth-Morris-Pratt Algorithm

Knuth-Morris-Pratt Algorithm searches for occurrences of a "word" within a main "text string"  by employing the observation that when a mismatch occurs, the word itself embodies sufficient information to determine where the next match could begin, thus bypassing re-examination of previously matched characters. 
Time complexity of Knuth-Morris-Pratt Algorithm is O(n+m), n is length of main string and m is length of the word/pattern string.

Knuth-Morris-Pratt Algorithm

---

Cpp/dynamicProgramming/roundrobin

Round Robin Scheduling is a scheduling algorithm used by the system to schedule CPU utilization. This is a preemptive algorithm. There exist a fixed time slice associated with each request called the quantum. The job scheduler saves the progress of the job that is being executed currently and moves to the next job present in the queue when a particular process is executed for a given time quantum.

roundrobin

---

Cpp/Luhn's Algorithm

The Luhn algorithm, also known as the modulus 10 or mod 10 algorithm, is a simple checksum formula used to validate a variety of identification numbers, such as credit card numbers, IMEI numbers, Canadian Social Insurance Numbers.

Luhn's Algorithm

---

Cpp/linked_list.cpp

-> insertion of node at head and tail
-> delete node at particular index or by value
-> print linked list and reverse of it.
-> reverse linked list
-> find middle node
-> delete middle node

Linked_List operations

---

Cpp/Binary Trees/Diameter-of-a-Binary-Tree

The diameter of a binary tree is the length of the longest path between
any two nodes in a tree. This path may or may not pass through the root.
The length of a path between two nodes is represented by the number of edges between them.

Diameter-of-a-binary-tree

---

Cpp/dynamicProgramming/CoinChange.cpp

Added Coin Change problem DP in c++

Added CoinChange dp problem in cpp

---

Cpp/Binary Trees/Level-Order-Traversal

A Level Order Traversal is a traversal which always traverses based on the level of the tree.

Level-Order-Traversal

---

InterviewDSA/leetcode/largestNumber.py

the largest number possible from a given set of numbers using python

largest number from a given set of numbers

---

c/type_of_character.c

A c code to find the type of character whether UPPER CASE or lower case numbers.

My contribution

---

Cpp/number_systems/binaryToDecimal.cpp
Cpp/number_systems/decimalToBinary.cpp
Cpp/number_systems/decimalToHexadecimal.cpp
Cpp/number_systems/decimalToOctal.cpp
Cpp/number_systems/hexadecimalToDecimal.cpp
Cpp/number_systems/octalToDecimal.cpp

I have added the binary to deimal,decimal to octal and decimal to hexadecimal and vice versa code in cpp

Added conversions

---

Dynamic Programming/0-1KnapsackProblem.cpp
Dynamic Programming/BoxStacking.cpp
Dynamic Programming/CoinChange.cpp
Dynamic Programming/CountPalindromicSubsequence.cpp
Dynamic Programming/EggDropping.cpp
Dynamic Programming/LongestCommonSubstring.cpp
Dynamic Programming/LongestPalindromicSubstring.cpp
Dynamic Programming/MaxLengthChain.cpp
Dynamic Programming/NthCatalanNumber.cpp
Dynamic Programming/PalindromicPartitioning.cpp
Dynamic Programming/ShortestCommonSupersequence.cpp
Dynamic Programming/SubsetSum.cpp
Dynamic Programming/UniqueBST.cpp
Dynamic Programming/WordBreakProblem.cpp
Dynamic Programming/editDistance.cpp
Dynamic Programming/lcs.cpp
Dynamic Programming/lis.cpp
Dynamic Programming/longestPathMatrix.cpp
Dynamic Programming/matrixChainMultliplication.cpp
Dynamic Programming/minimumSumPartition.cpp
Dynamic Programming/partitionProblem.cpp
Dynamic Programming/rodCutting.cpp

Hey admin, I have created a new directory named Dynamic Programming and added the most popular DP problems into it. Please take a look and let me know if there are some fixes needed to be done. If not then please merge this PR and attach the hacktoberfest-accepted tag to it.
Thank you :)

Added the most popular DP problems

---

c/studata.c

A simple c code to get the student's details like his complete address using functions and structures.

Contribution in c code

---

c/sorting/RadixSort.c

Radix sort is a sorting algorithm that sorts the elements by first grouping the individual digits of the same place value, it's implemented in large numbers.

Radix Sort

---

java/Strings/ReverseString.java

This is a program to reverse a string.

Add ReverseString.java

---

Cpp/Sorting/Bucket_Sort.cpp

Please review and merge the PR for Hacktoberfest

Added the code for Bucket_Sort

---

Cpp/Array - Data Structure/GeneralFlexibleArray.cpp

Contributed with a flexible array which can grow and shrink automatically as needed, implemented in C++.

GeneralFlexibleArray - Data Structure

---

InterviewDSA/leetcode/insertion_in_cll.cpp

Insertion in Circular LinkedList

---

Cpp/twosum.cpp

Created twosum.cpp
